Repository codestates-seb/seb40_pre_037, pull requests merged in 2022-11, with the labels that each got.

#95 👷 build : 빌드 관련 수정
  Client/package.json
Labels: 🌏 Deploy

#96 👷 build : 프론트 배포 테스트
  Client/.eslintrc.js
  Client/package-lock.json
  Client/package.json
  Client/src/App.js
  Client/src/Components/Ask.js
  Client/src/Components/LoginComponent.js
  Client/src/Components/QnA.js
  Client/src/atoms.js
  Client/src/components/AsideRight.js
  Client/src/components/Ask.js
  Client/src/components/Footer.js
  Client/src/components/List.js
  Client/src/components/LoginComponent.js
  Client/src/components/LoginedNav.js
  Client/src/components/Nav.js
  Client/src/components/QnA.js
  Client/src/components/SignupComponent.js
  Client/src/components/TextEditor.js
  Client/src/pages/BoardDetail.js
  Client/src/pages/LogIn.js
  Client/src/setupProxy.js
  Server/build.gradle
Labels: 🌏 Deploy

#97 🐛 fix : eslint 에러 수정
  Client/src/components/List.js
  Client/src/pages/LogIn.js
Labels: 🚨 BugFix

#98 👷 build : 프론트 배포 테스트용 설정
  Client/package.json
  Client/src/App.js
  Client/src/components/Ask.js
  Client/src/components/List.js
  Client/src/components/LoginComponent.js
  Client/src/components/LoginedNav.js
  Client/src/components/QnA.js
  Client/src/components/SignupComponent.js
  Client/src/setupProxy.js
  Client/vercel.json
Labels: 🌏 Deploy

#99 🐛 fix : url 실수 수정
  Client/src/components/QnA.js
Labels: 🌏 Deploy

#100 👷 build : 프론트 배포(1차 버그 잡는 용도)
  Client/package.json
  Client/src/App.js
  Client/src/components/Ask.js
  Client/src/components/List.js
  Client/src/components/LoginComponent.js
  Client/src/components/LoginedNav.js
  Client/src/components/QnA.js
  Client/src/components/SignupComponent.js
  Client/src/pages/LogIn.js
  Client/src/setupProxy.js
  Client/vercel.json
Labels: 🌏 Deploy

#101 🐛 fix : AsideLeft 레이아웃 수정
  Client/src/components/AsideLeft.js
  Client/src/pages/BoardList.js
Labels: 🚨 BugFix, 🖼 HTML&CSS

#102 🐛 fix : List 컴포넌트 오류 수정
  Client/src/atoms.js
  Client/src/components/List.js
Labels: 🚨 BugFix, ⛲ Feature

#103 🐛 fix : 콘솔로그 제거
  Client/src/components/Ask.js
  Client/src/components/LoginedNav.js
  Client/src/components/QnA.js
Labels: 🚨 BugFix

#104 🐛 fix : 시간 렌더링 오류 수정
  Client/src/components/List.js
Labels: 🚨 BugFix, ⛲ Feature

#105 🐛 fix : jwt-token 라이브러리 적용
  Client/src/components/LoginedNav.js
Labels: 🚨 BugFix

#106 👷 build : 빌드용 프록시로 변경
  Client/src/components/Ask.js
  Client/src/components/List.js
  Client/src/components/QnA.js
  Client/vercel.json
Labels: 🌏 Deploy

#107 👷 build : 빌드용 url 누락 수정
  Client/src/App.js
  Client/src/components/LoginComponent.js
  Client/src/components/LoginedNav.js
  Client/src/components/QnA.js
  Client/src/components/SignupComponent.js
Labels: 🚨 BugFix

#108 👷 build : 프론트 최종마감
  Client/src/atoms.js
  Client/src/components/AsideLeft.js
  Client/src/components/Ask.js
  Client/src/components/List.js
  Client/src/components/LoginedNav.js
  Client/src/components/QnA.js
  Client/src/pages/BoardList.js
  Client/src/setupProxy.js
Labels: 🌏 Deploy
